<ivy-module version="2.0" xmlns:e="http://ant.apache.org/ivy/extra" xmlns:ea="http://www.easyant.org">
    <info organisation="mustache" module="mustache" status="integration" >
        <description>A Java implementation of {{Mustache}} templates rendering.</description>
		<ea:build module="meta-build" revision="0.2"/>
    </info>
    <configurations>
        <conf name="default" visibility="public"/>
        <conf name="test" visibility="private"/>
    </configurations>
</ivy-module>
